name: first

on: push

jobs:
  build:
    name: Build and Test
    environment: E1
    runs-on: ubuntu-latest
    steps:
      - name: Env Test
        uses: actions/checkout@v4
      - name: Run a step for a secret
        run: "My secret is: $secrets.ENVIRONMENT_PASSWORD" 
        env:
          ENVIRONMENT_PASSWORD: ${{ secrets.ENVIRONMENT_PASSWORD }}
      
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps: 
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: ${{ vars.E2_VARIABLE }}
        
  job2:
    name: Second job
    runs-on: windows-latest
    steps: 
      - name: Step one
        run: ${{ vars.E3_SECRET_NAME }}
