name: first

on: push

jobs:
  build:
    name: Build and Test
    environment: E1
    runs-on: ubuntu-latest
    steps:
      - name: Hardcoded variable test
        uses: actions/checkout@v4
        with:
          hardcoded-secret: Hardcoded Secret
