name: aaron's cron test jobs

on:
  schedule:
    - cron: "25,30 16,17 * * *"
    - cron: "10 11,12 * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: aaron's sample cron job
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step was run on Tuesday"
      - name: Each time
        run: This is a step that will run every time
