name: aaron's cron test jobs

on:
  schedule:
    - cron: "36 13 * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: aaron's sample cron job
        run: echo "This step was run on Thursday"
