name: aaron's cron test jobs

on:
  schedule:
    - cron: "47 16 * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: aaron's sample cron job
        run: echo "This step was run on Tuesday"
      - name: Each time
        run: echo "This is a step that will run every time"
